service: metraf-api-gateway-hello

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  profile: artem
  stage: dev
  environment:
    DYNAMODB_TABLE: cities
  deploymentBucket:
    name: learning-serverless
  stackTags:
    Env: ${self:provider.stage}
  iamRoleStatements:
  - Effect: Allow
    Resource: "*"
    Action:
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
custom:
  serviceId: ${self:service}-${self:provider.stage}

package:
  exclude:
  - ../**
  include:
  - ../bin/**

functions:
  hello:
    handler: /bin/hello
    events:
    - http:
        path: hello
        method: get
  helloParam:
    handler: bin/helloParam
    events:
    - http:
        path: hello/{name}
        method: get
        request:
          parameters:
            paths:
            name: true
  putCity:
    handler: bin/putCity
    events:
    - http:
        path: city
        method: post
  listCities:
    handler: bin/listCities
    events:
    - http:
        path: city
        method: get
  getCity:
    handler: bin/getCity
    events:
    - http:
        path: city/{id}
        method: get
        request:
          parameters:
            paths:
            id: true
  deleteCity:
    handler: bin/deleteCity
    events:
    - http:
        path: city/{id}
        method: delete
        request:
          parameters:
            paths:
            id: true

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        GlobalSecondaryIndexes:
        - IndexName: city-index
          KeySchema:
          - AttributeName: city
            KeyType: HASH
          Projection:
            NonKeyAttributes:
            - country
            ProjectionType: INCLUDE
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
